name: CI
on:
  push:
    branches: [master]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:18
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - uses: actions/checkout@v4.1.1
      - name: LS everything
        run: ls -la
      - name: Tell node version
        run: node -v
      - name: Run script
        run: node index.js
