name: Command-Action

on:
  pull_request:
  issue_comment:
    types: [created]

jobs:
  cmd-check:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.command.outputs.branch }}
      commands: ${{ steps.command.outputs.command }}
    name: Bot
    steps:
      - uses: paritytech/cmd-action/check@main
        id: command

  cmd-run:
    needs: [cmd-check]
    if: ${{ github.event.issue.pull_request }}
    continue-on-error: true
    # We set the current machine here (to differ between ours and generic ones)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: ${{ fromJson(needs.cmd-check.outputs.commands) }}
    name: Run command
    steps:
      - uses: paritytech/cmd-action/run@error/report-with-comment
        with:
          branch: ${{ needs.cmd-check.outputs.branch }}
          command: ${{ matrix.command }}
          pr-number: ${{ github.event.issue.number || github.event.pull_request.number }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: cmd-action - changes
          branch: ${{ needs.cmd-check.outputs.branch }}
