name: Command-Action

on:
  pull_request:
  issue_comment:
    types: [created]

jobs:
  cmd-check:
    runs-on: ubuntu-latest
    outputs:
      commands: ${{ steps.command.outputs.commands }}
      branch: ${{ steps.command.outputs.branch }}
    name: Bot
    steps:
      - uses: paritytech/cmd-action/check@parse-comment
        id: command

  cmd-run:
    needs: [cmd-check]
    if: ${{ github.event.issue.pull_request }}
    continue-on-error: true
    # We set the current machine here (to differ between ours and generic ones)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: ${{ fromJson(needs.cmd-check.outputs.commands) }}
    name: Run command
    steps:
      - uses: paritytech/cmd-action/run@parse-comment
        with:
          branch: ${{ needs.cmd-check.outputs.branch }}
          command: ${{ matrix.command }}
      - name: Check changes
        run: |
          git config --system user.name command-bot
          git config --system user.email "github@users.noreply.github.com"
          git add .
          git commit -m "cmd-action - changes"
          git push origin $BRANCH
        env:
          BRANCH: ${{ needs.cmd-check.outputs.branch }}
