name: Review-Trigger

on:
  pull_request_target:

jobs:
  dismiss-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Dismiss Approvals
        env:
          GH_TOKEN: ${{ github.token }}
        run:  |
          gh api repos/${{ github.repository }}/pulls/${{ github.event.number }}/reviews \
          --jq '.[] | select(.state == "APPROVED") | .id' \
          | xargs -I '{}' gh api --method=PUT -f message="Dismissed due to PR edit." \
          repos/${{ github.repository }}/pulls/${{ github.event.number }}/reviews/'{}'/dismissals
