name: Mention fellows

on: 
  push:
    branches:
        - new-test

jobs:
  mention-fellows:
    runs-on: ubuntu-latest
    steps:
      - uses: paritytech/get-fellows-action@table
        id: fellows
      - name: Mention them
        run: |
          echo "The fellows are $FELLOWS"
        env:
          # the handles of the fellows separated by commas
          FELLOWS: ${{ steps.fellows.outputs.github-handles }}"
