name: Modify Changelog

on:
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Get Changed Files
        id: changed
        uses: foodee/pr-includes-file-change@master
        with:
          paths: ^CHANGELOG.md
      - name: Comment lack of CHANGELOG
        if: steps.changed.outputs.matched != 'true'
        run: gh pr comment $PR_NUMBER --body "Please modify the CHANGELOG.md file 🗂️"
        env:
          PR_NUMBER: context.issue.number
      - name: Fail
        if: steps.changed.outputs.matched != 'true' && !contains(github.event.pull_request.body, '[x] Does not require a CHANGELOG entry')
        run: exit 1
