on:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/a.yml
    secrets: inherit

  deploy:
    needs: build
    permissions:
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Call data
        run: echo "Result is $RESULT"
        env:
          RESULT: ${{ needs.build.outputs.result }}
      - run: echo "This run id is ${{ github.run_id }}"
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: example
          path: result
          run-id: ${{ needs.build.outputs.run }}
          github-token: ${{ github.secret }}
      - run: ls -la ./result
